### ISSUE TITLE
This App is not running in Android Kitkat 4.4 while working fine in Android 6.0

### ISSUE THREAD

**Issue by sumitmatta998** [njovy/AppRTCDemo#30]
09-26 12:32:58.096 15630-17914/org.appspot.apprtc D/de.tavendo.autobahn.WebSocketConnection: fail connection [code = INTERNAL_ERROR, reason = WebSockets internal error (java.lang.NullPointerException)
09-26 12:32:58.096 15630-17914/org.appspot.apprtc D/de.tavendo.autobahn.WebSocketReader: quit
09-26 12:32:58.096 15630-17956/org.appspot.apprtc D/de.tavendo.autobahn.WebSocketWriter: WebSocket writer ended.
09-26 12:32:58.096 15630-17914/org.appspot.apprtc D/WSChannelRTCClient: WebSocket connection closed. Code: INTERNAL_ERROR. Reason: WebSockets internal error (java.lang.NullPointerException). State: NEW
09-26 12:32:58.096 15630-17914/org.appspot.apprtc D/de.tavendo.autobahn.WebSocketConnection: worker threads stopped
09-26 12:32:58.096 15630-17914/org.appspot.apprtc D/de.tavendo.autobahn.WebSocketConnection: fail connection [code = INTERNAL_ERROR, reason = WebSockets internal error (java.lang.NullPointerException)
09-26 12:32:58.096 15630-17914/org.appspot.apprtc D/de.tavendo.autobahn.WebSocketReader: quit
09-26 12:32:58.096 15630-15630/org.appspot.apprtc D/CallRTCClient: Remote end hung up; dropping PeerConnection
09-26 12:32:58.096 15630-17942/org.appspot.apprtc D/de.tavendo.autobahn.WebSocketConnection: SocketThread exited.
09-26 12:32:58.116 15630-17914/org.appspot.apprtc W/MessageQueue: Handler (de.tavendo.autobahn.WebSocketWriter$ThreadHandler) {42e33318} sending message to a Handler on a dead thread
                                                                  java.lang.RuntimeException: Handler (de.tavendo.autobahn.WebSocketWriter$ThreadHandler) {42e33318} sending message to a Handler on a dead thread
                                                                      at android.os.MessageQueue.enqueueMessage(MessageQueue.java:320)
                                                                      at android.os.Handler.enqueueMessage(Handler.java:626)
                                                                      at android.os.Handler.sendMessageAtTime(Handler.java:595)
                                                                      at android.os.Handler.sendMessageDelayed(Handler.java:566)
                                                                      at android.os.Handler.sendMessage(Handler.java:503)
                                                                      at de.tavendo.autobahn.WebSocketWriter.forward(WebSocketWriter.java:95)
                                                                      at de.tavendo.autobahn.WebSocketConnection.failConnection(WebSocketConnection.java:109)
                                                                      at de.tavendo.autobahn.WebSocketConnection.handleMessage(WebSocketConnection.java:418)
                                                                      at de.tavendo.autobahn.WebSocketConnection.access$1(WebSocketConnection.java:344)
                                                                      at de.tavendo.autobahn.WebSocketConnection$ThreadHandler.handleMessage(WebSocketConnection.java:536)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                      at android.os.Looper.loop(Looper.java:146)
                                                                      at org.appspot.apprtc.util.LooperExecutor.run(LooperExecutor.java:44)
09-26 12:32:58.121 15630-15897/org.appspot.apprtc D/PCRTCClient: Closing peer connection.
09-26 12:32:58.131 15630-17914/org.appspot.apprtc W/MessageQueue: Handler (android.os.Handler) {42da7678} sending message to a Handler on a dead thread
                                                                  java.lang.RuntimeException: Handler (android.os.Handler) {42da7678} sending message to a Handler on a dead thread
                                                                      at android.os.MessageQueue.enqueueMessage(MessageQueue.java:320)
                                                                      at android.os.Handler.enqueueMessage(Handler.java:626)
                                                                      at android.os.Handler.sendMessageAtTime(Handler.java:595)
                                                                      at android.os.Handler.sendMessageDelayed(Handler.java:566)
                                                                      at android.os.Handler.post(Handler.java:326)
                                                                      at de.tavendo.autobahn.WebSocketConnection.failConnection(WebSocketConnection.java:121)
                                                                      at de.tavendo.autobahn.WebSocketConnection.handleMessage(WebSocketConnection.java:418)
                                                                      at de.tavendo.autobahn.WebSocketConnection.access$1(WebSocketConnection.java:344)
                                                                      at de.tavendo.autobahn.WebSocketConnection$ThreadHandler.handleMessage(WebSocketConnection.java:536)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                      at android.os.Looper.loop(Looper.java:146)
                                                                      at org.appspot.apprtc.util.LooperExecutor.run(LooperExecutor.java:44)
09-26 12:32:58.131 15630-17921/org.appspot.apprtc I/libjingle: (webrtcsession.cc:818): Session:7598169390711790190 Old state:STATE_SENTOFFER New state:STATE_CLOSED
09-26 12:32:58.131 15630-17921/org.appspot.apprtc D/PCRTCClient: IceGatheringState: COMPLETE
09-26 12:32:58.131 15630-17921/org.appspot.apprtc D/PCRTCClient: SignalingState: CLOSED
09-26 12:32:58.136 15630-17914/org.appspot.apprtc W/MessageQueue: Handler (android.os.Handler) {42da7678} sending message to a Handler on a dead thread
                                                                  java.lang.RuntimeException: Handler (android.os.Handler) {42da7678} sending message to a Handler on a dead thread
                                                                      at android.os.MessageQueue.enqueueMessage(MessageQueue.java:320)
                                                                      at android.os.Handler.enqueueMessage(Handler.java:626)
                                                                      at android.os.Handler.sendMessageAtTime(Handler.java:595)
                                                                      at android.os.Handler.sendMessageDelayed(Handler.java:566)
                                                                      at android.os.Handler.post(Handler.java:326)
                                                                      at de.tavendo.autobahn.WebSocketConnection.failConnection(WebSocketConnection.java:132)
                                                                      at de.tavendo.autobahn.WebSocketConnection.handleMessage(WebSocketConnection.java:418)
                                                                      at de.tavendo.autobahn.WebSocketConnection.access$1(WebSocketConnection.java:344)
                                                                      at de.tavendo.autobahn.WebSocketConnection$ThreadHandler.handleMessage(WebSocketConnection.java:536)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                      at android.os.Looper.loop(Looper.java:146)
                                                                      at org.appspot.apprtc.util.LooperExecutor.run(LooperExecutor.java:44)
09-26 12:32:58.136 15630-17914/org.appspot.apprtc D/WSChannelRTCClient: WebSocket connection closed. Code: INTERNAL_ERROR. Reason: WebSockets internal error (java.lang.NullPointerException). State: CLOSED
09-26 12:32:58.136 15630-17914/org.appspot.apprtc W/LooperExecutor: Running looper executor without calling requestStart()
09-26 12:32:58.136 15630-17914/org.appspot.apprtc D/de.tavendo.autobahn.WebSocketConnection: worker threads stopped
09-26 12:32:58.136 15630-17914/org.appspot.apprtc D/WSRTCClient: Disconnect. Room state: CONNECTED
09-26 12:32:58.136 15630-17914/org.appspot.apprtc D/WSRTCClient: Closing room.
09-26 12:32:58.136 15630-17914/org.appspot.apprtc D/WSRTCClient: C->GAE: https://apprtc.appspot.com/leave/2567899654467/48538717
09-26 12:32:58.141 15630-17914/org.appspot.apprtc D/WSChannelRTCClient: Disconnect WebSocket. State: CLOSED
09-26 12:32:58.141 15630-17914/org.appspot.apprtc D/WSChannelRTCClient: Disconnecting WebSocket done.
09-26 12:32:58.141 15630-17914/org.appspot.apprtc D/LooperExecutor: Looper thread finished.

**Comment by sumitmatta998** [comment]
`09-26 12:32:58.096 15630-17914/org.appspot.apprtc D/de.tavendo.autobahn.WebSocketConnection: fail connection [code = INTERNAL_ERROR, reason = WebSockets internal error (java.lang.NullPointerException)
09-26 12:32:58.096 15630-17914/org.appspot.apprtc D/de.tavendo.autobahn.WebSocketReader: quit
09-26 12:32:58.096 15630-17956/org.appspot.apprtc D/de.tavendo.autobahn.WebSocketWriter: WebSocket writer ended.
09-26 12:32:58.096 15630-17914/org.appspot.apprtc D/WSChannelRTCClient: WebSocket connection closed. Code: INTERNAL_ERROR. Reason: WebSockets internal error (java.lang.NullPointerException). State: NEW
09-26 12:32:58.096 15630-17914/org.appspot.apprtc D/de.tavendo.autobahn.WebSocketConnection: worker threads stopped
09-26 12:32:58.096 15630-17914/org.appspot.apprtc D/de.tavendo.autobahn.WebSocketConnection: fail connection [code = INTERNAL_ERROR, reason = WebSockets internal error (java.lang.NullPointerException)
09-26 12:32:58.096 15630-17914/org.appspot.apprtc D/de.tavendo.autobahn.WebSocketReader: quit
09-26 12:32:58.096 15630-15630/org.appspot.apprtc D/CallRTCClient: Remote end hung up; dropping PeerConnection
09-26 12:32:58.096 15630-17942/org.appspot.apprtc D/de.tavendo.autobahn.WebSocketConnection: SocketThread exited.
09-26 12:32:58.116 15630-17914/org.appspot.apprtc W/MessageQueue: Handler (de.tavendo.autobahn.WebSocketWriter$ThreadHandler) {42e33318} sending message to a Handler on a dead thread
                                                                  java.lang.RuntimeException: Handler (de.tavendo.autobahn.WebSocketWriter$ThreadHandler) {42e33318} sending message to a Handler on a dead thread
                                                                      at android.os.MessageQueue.enqueueMessage(MessageQueue.java:320)
                                                                      at android.os.Handler.enqueueMessage(Handler.java:626)
                                                                      at android.os.Handler.sendMessageAtTime(Handler.java:595)
                                                                      at android.os.Handler.sendMessageDelayed(Handler.java:566)
                                                                      at android.os.Handler.sendMessage(Handler.java:503)
                                                                      at de.tavendo.autobahn.WebSocketWriter.forward(WebSocketWriter.java:95)
                                                                      at de.tavendo.autobahn.WebSocketConnection.failConnection(WebSocketConnection.java:109)
                                                                      at de.tavendo.autobahn.WebSocketConnection.handleMessage(WebSocketConnection.java:418)
                                                                      at de.tavendo.autobahn.WebSocketConnection.access$1(WebSocketConnection.java:344)
                                                                      at de.tavendo.autobahn.WebSocketConnection$ThreadHandler.handleMessage(WebSocketConnection.java:536)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                      at android.os.Looper.loop(Looper.java:146)
                                                                      at org.appspot.apprtc.util.LooperExecutor.run(LooperExecutor.java:44)
09-26 12:32:58.121 15630-15897/org.appspot.apprtc D/PCRTCClient: Closing peer connection.
09-26 12:32:58.131 15630-17914/org.appspot.apprtc W/MessageQueue: Handler (android.os.Handler) {42da7678} sending message to a Handler on a dead thread
                                                                  java.lang.RuntimeException: Handler (android.os.Handler) {42da7678} sending message to a Handler on a dead thread
                                                                      at android.os.MessageQueue.enqueueMessage(MessageQueue.java:320)
                                                                      at android.os.Handler.enqueueMessage(Handler.java:626)
                                                                      at android.os.Handler.sendMessageAtTime(Handler.java:595)
                                                                      at android.os.Handler.sendMessageDelayed(Handler.java:566)
                                                                      at android.os.Handler.post(Handler.java:326)
                                                                      at de.tavendo.autobahn.WebSocketConnection.failConnection(WebSocketConnection.java:121)
                                                                      at de.tavendo.autobahn.WebSocketConnection.handleMessage(WebSocketConnection.java:418)
                                                                      at de.tavendo.autobahn.WebSocketConnection.access$1(WebSocketConnection.java:344)
                                                                      at de.tavendo.autobahn.WebSocketConnection$ThreadHandler.handleMessage(WebSocketConnection.java:536)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                      at android.os.Looper.loop(Looper.java:146)
                                                                      at org.appspot.apprtc.util.LooperExecutor.run(LooperExecutor.java:44)
09-26 12:32:58.131 15630-17921/org.appspot.apprtc I/libjingle: (webrtcsession.cc:818): Session:7598169390711790190 Old state:STATE_SENTOFFER New state:STATE_CLOSED
09-26 12:32:58.131 15630-17921/org.appspot.apprtc D/PCRTCClient: IceGatheringState: COMPLETE
09-26 12:32:58.131 15630-17921/org.appspot.apprtc D/PCRTCClient: SignalingState: CLOSED
09-26 12:32:58.136 15630-17914/org.appspot.apprtc W/MessageQueue: Handler (android.os.Handler) {42da7678} sending message to a Handler on a dead thread
                                                                  java.lang.RuntimeException: Handler (android.os.Handler) {42da7678} sending message to a Handler on a dead thread
                                                                      at android.os.MessageQueue.enqueueMessage(MessageQueue.java:320)
                                                                      at android.os.Handler.enqueueMessage(Handler.java:626)
                                                                      at android.os.Handler.sendMessageAtTime(Handler.java:595)
                                                                      at android.os.Handler.sendMessageDelayed(Handler.java:566)
                                                                      at android.os.Handler.post(Handler.java:326)
                                                                      at de.tavendo.autobahn.WebSocketConnection.failConnection(WebSocketConnection.java:132)
                                                                      at de.tavendo.autobahn.WebSocketConnection.handleMessage(WebSocketConnection.java:418)
                                                                      at de.tavendo.autobahn.WebSocketConnection.access$1(WebSocketConnection.java:344)
                                                                      at de.tavendo.autobahn.WebSocketConnection$ThreadHandler.handleMessage(WebSocketConnection.java:536)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                      at android.os.Looper.loop(Looper.java:146)
                                                                      at org.appspot.apprtc.util.LooperExecutor.run(LooperExecutor.java:44)
09-26 12:32:58.136 15630-17914/org.appspot.apprtc D/WSChannelRTCClient: WebSocket connection closed. Code: INTERNAL_ERROR. Reason: WebSockets internal error (java.lang.NullPointerException). State: CLOSED
09-26 12:32:58.136 15630-17914/org.appspot.apprtc W/LooperExecutor: Running looper executor without calling requestStart()
09-26 12:32:58.136 15630-17914/org.appspot.apprtc D/de.tavendo.autobahn.WebSocketConnection: worker threads stopped
09-26 12:32:58.136 15630-17914/org.appspot.apprtc D/WSRTCClient: Disconnect. Room state: CONNECTED
09-26 12:32:58.136 15630-17914/org.appspot.apprtc D/WSRTCClient: Closing room.
09-26 12:32:58.136 15630-17914/org.appspot.apprtc D/WSRTCClient: C->GAE: https://apprtc.appspot.com/leave/2567899654467/48538717
09-26 12:32:58.141 15630-17914/org.appspot.apprtc D/WSChannelRTCClient: Disconnect WebSocket. State: CLOSED
09-26 12:32:58.141 15630-17914/org.appspot.apprtc D/WSChannelRTCClient: Disconnecting WebSocket done.
09-26 12:32:58.141 15630-17914/org.appspot.apprtc D/LooperExecutor: Looper thread finished.`
