### ISSUE TITLE
Can not work in android 4.4 but in android 6.0 is fine

### ISSUE THREAD

**Issue by SanBeHappy** [njovy/AppRTCDemo#74]
E/AppRTCMobileActivity: Fatal error: Failed to create EGL context: 0x3009
                                                                        
                                                                        java.lang.RuntimeException: Unable to start activity ComponentInfo{org.appspot.apprtc/org.appspot.apprtc.CallActivity}: java.lang.RuntimeException: java.lang.RuntimeException: Failed to create EGL context: 0x3009
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2195)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
                                                                            at android.app.ActivityThread.access$800(ActivityThread.java:135)
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                            at android.os.Looper.loop(Looper.java:136)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5017)
                                                                            at java.lang.reflect.Method.invokeNative(Native Method)
                                                                            at java.lang.reflect.Method.invoke(Method.java:515)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                                                                            at dalvik.system.NativeStart.main(Native Method)
                                                                         Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Failed to create EGL context: 0x3009
                                                                            at org.webrtc.EglBase14.createEglContext(EglBase14.java:272)
                                                                            at org.webrtc.EglBase14.<init>(EglBase14.java:69)
                                                                            at org.webrtc.EglBase.create(EglBase.java:91)
                                                                            at org.webrtc.EglRenderer.lambda$init$0$EglRenderer(EglRenderer.java:189)
                                                                            at org.webrtc.EglRenderer$$Lambda$0.run(Unknown Source)
                                                                            at org.webrtc.ThreadUtils$5.call(ThreadUtils.java:209)
                                                                            at org.webrtc.ThreadUtils$5.call(ThreadUtils.java:206)
                                                                            at org.webrtc.ThreadUtils$4.run(ThreadUtils.java:183)
                                                                            at android.os.Handler.handleCallback(Handler.java:733)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                            at android.os.Looper.loop(Looper.java:136)
                                                                            at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                            at org.webrtc.ThreadUtils.invokeAtFrontUninterruptibly(ThreadUtils.java:194)
                                                                            at org.webrtc.ThreadUtils.invokeAtFrontUninterruptibly(ThreadUtils.java:206)
                                                                            at org.webrtc.EglRenderer.init(EglRenderer.java:180)
                                                                            at org.webrtc.SurfaceEglRenderer.init(SurfaceEglRenderer.java:61)
                                                                            at org.webrtc.SurfaceViewRenderer.init(SurfaceViewRenderer.java:88)
                                                                            at org.webrtc.SurfaceViewRenderer.init(SurfaceViewRenderer.java:72)
                                                                            at org.appspot.apprtc.CallActivity.onCreate(CallActivity.java:276)
                                                                            at android.app.Activity.performCreate(Activity.java:5231)
                                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245) 
                                                                            at android.app.ActivityThread.access$800(ActivityThread.java:135) 
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                            at android.os.Looper.loop(Looper.java:136) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5017) 
                                                                            at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                            at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
                                                                            at dalvik.system.NativeStart.main(Native Method) 
                                                                         Caused by: java.lang.RuntimeException: Failed to create EGL context: 0x3009
                                                                            at org.webrtc.EglBase14.createEglContext(EglBase14.java:272)
                                                                            at org.webrtc.EglBase14.<init>(EglBase14.java:69)
                                                                            at org.webrtc.EglBase.create(EglBase.java:91)
                                                                            at org.webrtc.EglRenderer.lambda$init$0$EglRenderer(EglRenderer.java:189)
                                                                            at org.webrtc.EglRenderer$$Lambda$0.run(Unknown Source)
                                                                            at org.webrtc.ThreadUtils$5.call(ThreadUtils.java:209)
                                                                            at org.webrtc.ThreadUtils$5.call(ThreadUtils.java:206)
                                                                            at org.webrtc.ThreadUtils$4.run(ThreadUtils.java:183)
                                                                            at android.os.Handler.handleCallback(Handler.java:733)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                            at android.os.Looper.loop(Looper.java:136)
                                                                            at android.os.HandlerThread.run(HandlerThread.java:61)

how can i slove this problem?

**Comment by BlackBlind567** [comment]
try to change lower level dependency.
